apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "8000"