apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todoapp-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50